/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FCodeRouteImport } from './routes/f.$code'
import { Route as FormSlugRouteImport } from './routes/form.$slug'
import { Route as FormsIdIndexRouteImport } from './routes/forms.$id.index'
import { Route as FormsIdResponsesIndexRouteImport } from './routes/forms.$id.responses.index'
import { Route as FormsIdResponsesSeqRouteImport } from './routes/forms.$id.responses.$seq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FCodeRoute = FCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const FormSlugRoute = FormSlugRouteImport.update({
  id: '/form/$slug',
  path: '/form/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdIndexRoute = FormsIdIndexRouteImport.update({
  id: '/forms/$id/',
  path: '/forms/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdResponsesIndexRoute = FormsIdResponsesIndexRouteImport.update({
  id: '/forms/$id/responses/',
  path: '/forms/$id/responses/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIdResponsesSeqRoute = FormsIdResponsesSeqRouteImport.update({
  id: '/forms/$id/responses/$seq',
  path: '/forms/$id/responses/$seq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/f/$code': typeof FCodeRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms/$id/': typeof FormsIdIndexRoute
  '/forms/$id/responses/$seq': typeof FormsIdResponsesSeqRoute
  '/forms/$id/responses/': typeof FormsIdResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/f/$code': typeof FCodeRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms/$id': typeof FormsIdIndexRoute
  '/forms/$id/responses/$seq': typeof FormsIdResponsesSeqRoute
  '/forms/$id/responses': typeof FormsIdResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/f/$code': typeof FCodeRoute
  '/form/$slug': typeof FormSlugRoute
  '/forms/$id/': typeof FormsIdIndexRoute
  '/forms/$id/responses/$seq': typeof FormsIdResponsesSeqRoute
  '/forms/$id/responses/': typeof FormsIdResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/f/$code'
    | '/form/$slug'
    | '/forms/$id/'
    | '/forms/$id/responses/$seq'
    | '/forms/$id/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/f/$code'
    | '/form/$slug'
    | '/forms/$id'
    | '/forms/$id/responses/$seq'
    | '/forms/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/f/$code'
    | '/form/$slug'
    | '/forms/$id/'
    | '/forms/$id/responses/$seq'
    | '/forms/$id/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FCodeRoute: typeof FCodeRoute
  FormSlugRoute: typeof FormSlugRoute
  FormsIdIndexRoute: typeof FormsIdIndexRoute
  FormsIdResponsesSeqRoute: typeof FormsIdResponsesSeqRoute
  FormsIdResponsesIndexRoute: typeof FormsIdResponsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$code': {
      id: '/f/$code'
      path: '/f/$code'
      fullPath: '/f/$code'
      preLoaderRoute: typeof FCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$slug': {
      id: '/form/$slug'
      path: '/form/$slug'
      fullPath: '/form/$slug'
      preLoaderRoute: typeof FormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id/': {
      id: '/forms/$id/'
      path: '/forms/$id'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof FormsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id/responses/': {
      id: '/forms/$id/responses/'
      path: '/forms/$id/responses'
      fullPath: '/forms/$id/responses/'
      preLoaderRoute: typeof FormsIdResponsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$id/responses/$seq': {
      id: '/forms/$id/responses/$seq'
      path: '/forms/$id/responses/$seq'
      fullPath: '/forms/$id/responses/$seq'
      preLoaderRoute: typeof FormsIdResponsesSeqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FCodeRoute: FCodeRoute,
  FormSlugRoute: FormSlugRoute,
  FormsIdIndexRoute: FormsIdIndexRoute,
  FormsIdResponsesSeqRoute: FormsIdResponsesSeqRoute,
  FormsIdResponsesIndexRoute: FormsIdResponsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
